package de.uka.ipd.sdq.beagle.core.failurehandling;

/**
 * Interface for instances resolving failures.
 *
 * @author Joshua Gleitze
 */
public interface FailureResolver {

	/**
	 * Reports a failure to this resolver. The resolver will choose the appropriate action
	 * to resove the failuer. This may include calling the recover functions potentially
	 * provided through {@code report}. If they are claade, this method will return the
	 * value generated by the recover functions. If the {@code report} describes a
	 * non-recoverable failure, this method will not return. This method might also not
	 * return if the handler thinks it’s not appropriate to continue.
	 *
	 * @param <RECOVER_TYPE> The recover value’s type.
	 * @param report Information about the failure. Will never be {@code null}.
	 * @param reporterName The name of the instance reporting the failure. Will never be
	 *            {@code null}
	 * @return The value the reporter should use instead of the one that was expected to
	 *         be generated by the failed action. Is created by the recover functions in
	 *         {@code report}.
	 */
	<RECOVER_TYPE> RECOVER_TYPE handle(final FailureReport<RECOVER_TYPE> report, final String reporterName);
}
